import type { MemoryInput } from './memories'

export const DEFAULT_MEMORIES: MemoryInput[] = [
  {
    title: 'First Meet After 702 Days ❤️',
    category: 'Milestone',
    memory_date: '2026-07-05',
    location_name: 'First Meet',
    description: 'Our first meet after 702 long days apart. An unforgettable beginning to our story.',
  },
  {
    title: '1st Official Date at Kala Bhoomi',
    category: 'Date',
    memory_date: '2026-07-12',
    memory_time: '11:30:00',
    location_name: 'Kala Bhoomi',
    description: 'Our 1st official date together at Kala Bhoomi crafts museum. (11:30 AM – 2:15 PM)',
  },
  {
    title: 'Lingaraj & Rajarani Temple Visit',
    category: 'Date',
    memory_date: '2026-07-17',
    memory_time: '16:00:00',
    location_name: 'Lingaraj & Rajarani Temple',
    description: 'Peaceful and divine evening visiting Lingaraj and Rajarani temples. (4:00 PM – 8:30 PM)',
  },
  {
    title: '1st Movie Together: Evil Dead Burn 🎬',
    category: 'Date',
    memory_date: '2026-07-19',
    memory_time: '15:00:00',
    location_name: 'Cinema',
    description: 'Our 1st movie together watching Evil Dead Burn. (3:00 PM – 5:50 PM)',
  },
  {
    title: '2nd Movie Together: Dhamaal 4 🍿',
    category: 'Date',
    memory_date: '2026-07-22',
    memory_time: '15:00:00',
    location_name: 'Cinema',
    description: 'Our 2nd movie together watching Dhamaal 4. (3:00 PM – 6:25 PM)',
  },
  {
    title: 'Serene Walk at Jaydev Vatika 🌿',
    category: 'Moment',
    memory_date: '2026-07-25',
    memory_time: '17:00:00',
    location_name: 'Jaydev Vatika',
    description: 'A beautiful evening strolling through Jaydev Vatika park. (5:00 PM – 8:00 PM)',
  },
  {
    title: 'Proposal Day at Janaki Ballav Pattnaik Park 💍❤️',
    category: 'Milestone',
    memory_date: '2026-07-29',
    memory_time: '16:00:00',
    location_name: 'Janaki Ballav Pattnaik Park, Khordha',
    description: 'The magical moment at Janaki Ballav Pattnaik Park in Khordha where we said yes to forever. Proposal day! (4:00 PM – 9:15 PM)',
  },
  {
    title: '1st Date as Couple: ISKCON & Botanical Garden 🌸',
    category: 'Date',
    memory_date: '2026-07-31',
    memory_time: '16:15:00',
    location_name: 'ISKCON & Botanical Garden, Nayapalli',
    description: '1st date as a couple! Visiting ISKCON Nayapalli and Botanical Garden Nayapalli. (4:15 PM – 9:45 PM)',
  },
  {
    title: 'Back to Janaki Ballav Pattnaik Park 🌳',
    category: 'Moment',
    memory_date: '2026-08-02',
    memory_time: '17:30:00',
    location_name: 'Janaki Ballav Pattnaik Park, Khordha',
    description: 'Revisiting Janaki Ballav Pattnaik Park in Khordha for a sweet evening conversation. (5:30 PM – 8:30 PM)',
  },
  {
    title: '3rd Movie (1st as Couple): Jan Neta 🎬',
    category: 'Date',
    memory_date: '2026-08-04',
    memory_time: '14:00:00',
    location_name: 'Cinema',
    description: '3rd movie together and 1st as a couple: Jan Neta (3 hr 3 mins + 1 hour).',
  },
  {
    title: 'Lovely Afternoon Park Date 🍃',
    category: 'Moment',
    memory_date: '2026-08-07',
    memory_time: '16:00:00',
    location_name: 'Park',
    description: 'Park date together spending 3.5 – 4 hours holding hands and chatting.',
  },
  {
    title: '4th Movie Date: Jan Neta 🍿',
    category: 'Date',
    memory_date: '2026-08-08',
    memory_time: '14:30:00',
    location_name: 'Cinema',
    description: '4th movie together: Jan Neta (3.3 hrs + 1 hr).',
  },
  {
    title: '5th Movie Date: Jan Neta',
    category: 'Date',
    memory_date: '2026-08-09',
    memory_time: '14:30:00',
    location_name: 'Cinema',
    description: '5th movie together: Jan Neta (3.3 hrs + 1 hr).',
  },
  {
    title: '6th Movie Date: Spiderman 🕷️',
    category: 'Date',
    memory_date: '2026-08-11',
    memory_time: '15:00:00',
    location_name: 'Cinema',
    description: '6th movie together: Spiderman (1 hr 45 min + 30 min).',
  },
  {
    title: '7th Movie: Awarapan & Independence Day 🇮🇳',
    category: 'Date',
    memory_date: '2026-08-15',
    memory_time: '13:00:00',
    location_name: 'Cinema',
    description: '7th movie date watching Awarapan on Independence Day. (2 hr 20 min + 1 hr + 1.5 hr).',
  },
  {
    title: '5-Hour Park Date 🏞️',
    category: 'Moment',
    memory_date: '2026-08-19',
    memory_time: '15:00:00',
    location_name: 'Park',
    description: 'A peaceful, joyful 5 hours spent together in the park.',
  },
  {
    title: 'Double Movie & Lunch: Insidious + Batwara 🎥',
    category: 'Date',
    memory_date: '2026-08-22',
    memory_time: '12:00:00',
    location_name: 'Cinema & Restaurant',
    description: 'Movie marathon! 8th movie Insidious (1 hr 46 min + 20 min) & 9th movie Batwara (2 hr 24 min) + 1.5 hr lunch.',
  },
  {
    title: 'Devotional Evening: ISKCON & Ram Mandir 🛕',
    category: 'Date',
    memory_date: '2026-08-26',
    memory_time: '16:30:00',
    location_name: 'ISKCON & Ram Mandir',
    description: 'Seeking divine blessings together at ISKCON and Ram Mandir.',
  },
  {
    title: 'Longest Date Ever: 7.5 Hours in the Park ⏳💖',
    category: 'Moment',
    memory_date: '2026-08-27',
    memory_time: '13:00:00',
    location_name: 'Park',
    description: 'Our longest date record: 7.5 hours spent together in the park enjoying every second.',
  },
  {
    title: '10th Movie Milestone: Toxic 🎞️',
    category: 'Date',
    memory_date: '2026-08-28',
    memory_time: '16:00:00',
    location_name: 'Cinema',
    description: 'Double digits! Movie #10: Toxic.',
  },
  {
    title: '1 Month Anniversary ❤️',
    category: 'Milestone',
    memory_date: '2026-08-29',
    memory_time: '18:00:00',
    location_name: 'Together',
    description: '1 month anniversary since our proposal on 29th July. Happy 1 Month!',
  },
  {
    title: 'Sweet Reunion, Movie & Ganesh Puja Mela 🎪❤️',
    category: 'Trip',
    memory_date: '2026-09-14',
    memory_time: '15:30:00',
    location_name: 'Ganesh Puja Mela',
    description: 'A sweet reunion ❤️, a movie date, and festive Ganesh Puja mela together.',
  },
  {
    title: '2nd Month Anniversary ❤️ Today!',
    category: 'Milestone',
    memory_date: '2026-09-29',
    memory_time: '18:00:00',
    location_name: 'Together',
    description: '2nd month anniversary ❤️! Celebrating our journey together.',
  },
]
